objtype=riscv64

</$objtype/mkfile

all:V: main.out main.bin

# must include -s to strip all plan9 symbols for a true binary output
main.bin: start.$O main.$O volatile.$O
	$LD $DFLAGS -s -H 1 -T 0x41000000 -E _start -o main.bin start.$O main.$O volatile.$O

main.out: start.$O main.$O volatile.$O
	$LD $DFLAGS -T 0x41000000 -E _start -o main.out start.$O main.$O volatile.$O

main.$O: main.c
	$CC $CFLAGS main.c

volatile.$O: volatile.c
	$CC $CFLAGS volatile.c

start.$O: start.s
	$AS  start.s

clean:V:
	rm -f main.bin main.out main.$O volatile.$O start.$O
