objtype=riscv64

</$objtype/mkfile

all:V: main.out main.bin

# must include -s to strip all plan9 symbols for a true binary output
main.bin: start.$O csrtest.$O regtest.$O arithtest.$O main.$O
	$LD $DFLAGS -s -H 1 -T 0x41000000 -E _start -o main.bin start.$O csrtest.$O regtest.$O arithtest.$O main.$O

main.out: start.$O csrtest.$O regtest.$O arithtest.$O main.$O
	$LD $DFLAGS -T 0x41000000 -E _start -o main.out start.$O csrtest.$O regtest.$O arithtest.$O main.$O

main.$O: main.c
	$CC $CFLAGS main.c

csrtest.$O: csrtest.s
	$AS  csrtest.s

regtest.$O: regtest.s
	$AS  regtest.s

arithtest.$O: arithtest.s
	$AS  arithtest.s

start.$O: start.s
	$AS  start.s

clean:V:
	rm -f main.bin main.out main.$O csrtest.$O regtest.$O arithtest.$O start.$O
